on:
  push:
    branches:
      - master

jobs:
  build_css:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source Git branch
        uses: actions/checkout@v2
        with:
            ref: master
            fetch-depth: 10
            submodules: true

      - name: Make destination directory for compiled CSS
        run: mkdir -vp /tmp/spongerobert.com/css

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.4.9
        with:
          source: _scss/face.scss
          destination: /tmp/spongerobert.com/css/face.css

      - name: Checkout destination Git branch
        uses: actions/checkout@v2
        with:
            ref: gh-pages
            fetch-depth: 1

      - name: Move compiled CSS to path within gh-pages branch
        run: mv /tmp/spongerobert.com/css /

      - name: Add and Commit changes to gh-pages branch
        run: |
          git config --local user.email 'action@github.com'
          git config --local user.name 'GitHub Action'
          git add css/*
          git commit -m 'Updates compiled CSS files'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
